# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteNotification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RemoteNotification
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  target 'RemoteNotificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemoteNotificationUITests' do
    # Pods for testing
  end

end
