# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseNotice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseNotice
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Analytics'

  target 'FirebaseNoticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseNoticeUITests' do
    # Pods for testing
  end

end
